### ISSUE TITLE
renderResources with PHP 8 - blank output

### ISSUE THREAD

**Issue by ebene11** [opengeek/renderResources#6]
I try renderResources with PHP 8 (MODX 2.8.3) and get a blank output. Change PHP to 7.4 and everything is fine.

**Comment by halftrainedharry** [comment]
The code uses the _each_ function that was removed in PHP 8.

https://github.com/opengeek/renderResources/blob/f5c2d0174e1389811c2208d04f81fa35862699d7/core/components/renderresources/snippet.renderresources.php#L374

If you replace line 374 in the snippet with
```
foreach($sorts as $sort => $dir) {
```
it should work again.
